package beans;
// Generated 12/03/2018 12:07:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatEstado generated by hbm2java
 */
@Entity
@Table(name="cat_estado"
    ,catalog="consultorio_dental"
)
public class CatEstado  implements java.io.Serializable {


     private Integer idEstado;
     private String estado;
     private Boolean activo;
     private Set<DataDireccion> dataDireccions = new HashSet<DataDireccion>(0);

    public CatEstado() {
    }

    public CatEstado(String estado, Boolean activo, Set<DataDireccion> dataDireccions) {
       this.estado = estado;
       this.activo = activo;
       this.dataDireccions = dataDireccions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_estado", unique=true, nullable=false)
    public Integer getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }

    
    @Column(name="estado", length=100)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="activo")
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catEstado")
    public Set<DataDireccion> getDataDireccions() {
        return this.dataDireccions;
    }
    
    public void setDataDireccions(Set<DataDireccion> dataDireccions) {
        this.dataDireccions = dataDireccions;
    }




}


