package beans;
// Generated 12/03/2018 12:07:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatPais generated by hbm2java
 */
@Entity
@Table(name="cat_pais"
    ,catalog="consultorio_dental"
)
public class CatPais  implements java.io.Serializable {


     private Integer idPais;
     private String pais;
     private Boolean activo;
     private Set<DataDireccion> dataDireccions = new HashSet<DataDireccion>(0);

    public CatPais() {
    }

    public CatPais(String pais, Boolean activo, Set<DataDireccion> dataDireccions) {
       this.pais = pais;
       this.activo = activo;
       this.dataDireccions = dataDireccions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_pais", unique=true, nullable=false)
    public Integer getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(Integer idPais) {
        this.idPais = idPais;
    }

    
    @Column(name="pais", length=100)
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }

    
    @Column(name="activo")
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catPais")
    public Set<DataDireccion> getDataDireccions() {
        return this.dataDireccions;
    }
    
    public void setDataDireccions(Set<DataDireccion> dataDireccions) {
        this.dataDireccions = dataDireccions;
    }




}


