package beans;
// Generated 12/03/2018 12:07:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatRoles generated by hbm2java
 */
@Entity
@Table(name="cat_roles"
    ,catalog="consultorio_dental"
)
public class CatRoles  implements java.io.Serializable {


     private Integer idRol;
     private String rol;
     private Boolean activo;
     private Set<DataUsuario> dataUsuarios = new HashSet<DataUsuario>(0);

    public CatRoles() {
    }

    public CatRoles(String rol, Boolean activo, Set<DataUsuario> dataUsuarios) {
       this.rol = rol;
       this.activo = activo;
       this.dataUsuarios = dataUsuarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_rol", unique=true, nullable=false)
    public Integer getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }

    
    @Column(name="rol", length=20)
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }

    
    @Column(name="activo")
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catRoles")
    public Set<DataUsuario> getDataUsuarios() {
        return this.dataUsuarios;
    }
    
    public void setDataUsuarios(Set<DataUsuario> dataUsuarios) {
        this.dataUsuarios = dataUsuarios;
    }




}


