package beans;
// Generated 12/03/2018 12:07:35 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DataPersona generated by hbm2java
 */
@Entity
@Table(name="data_persona"
    ,catalog="consultorio_dental"
)
public class DataPersona  implements java.io.Serializable {


     private Integer idPersona;
     private DataContacto dataContacto;
     private DataDireccion dataDireccion;
     private String nombre;
     private String apellidoPaterno;
     private String apelidoMaterno;
     private Date fechaNacimiento;
     private String curp;
     private boolean activo;
     private Set<DataUsuario> dataUsuarios = new HashSet<DataUsuario>(0);

    public DataPersona() {
    }

	
    public DataPersona(boolean activo) {
        this.activo = activo;
    }
    public DataPersona(DataContacto dataContacto, DataDireccion dataDireccion, String nombre, String apellidoPaterno, String apelidoMaterno, Date fechaNacimiento, String curp, boolean activo, Set<DataUsuario> dataUsuarios) {
       this.dataContacto = dataContacto;
       this.dataDireccion = dataDireccion;
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apelidoMaterno = apelidoMaterno;
       this.fechaNacimiento = fechaNacimiento;
       this.curp = curp;
       this.activo = activo;
       this.dataUsuarios = dataUsuarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_persona", unique=true, nullable=false)
    public Integer getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="datos_contacto")
    public DataContacto getDataContacto() {
        return this.dataContacto;
    }
    
    public void setDataContacto(DataContacto dataContacto) {
        this.dataContacto = dataContacto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="direccion")
    public DataDireccion getDataDireccion() {
        return this.dataDireccion;
    }
    
    public void setDataDireccion(DataDireccion dataDireccion) {
        this.dataDireccion = dataDireccion;
    }

    
    @Column(name="nombre")
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido_paterno")
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }

    
    @Column(name="apelido_materno")
    public String getApelidoMaterno() {
        return this.apelidoMaterno;
    }
    
    public void setApelidoMaterno(String apelidoMaterno) {
        this.apelidoMaterno = apelidoMaterno;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_nacimiento", length=10)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    
    @Column(name="curp", length=18)
    public String getCurp() {
        return this.curp;
    }
    
    public void setCurp(String curp) {
        this.curp = curp;
    }

    
    @Column(name="activo", nullable=false)
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dataPersona")
    public Set<DataUsuario> getDataUsuarios() {
        return this.dataUsuarios;
    }
    
    public void setDataUsuarios(Set<DataUsuario> dataUsuarios) {
        this.dataUsuarios = dataUsuarios;
    }




}


