package beans;
// Generated 12/03/2018 12:07:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DataContacto generated by hbm2java
 */
@Entity
@Table(name="data_contacto"
    ,catalog="consultorio_dental"
)
public class DataContacto  implements java.io.Serializable {


     private Integer idContacto;
     private String correoElectronico;
     private String telefonoMovil;
     private String telefonoFijo;
     private Set<DataPersona> dataPersonas = new HashSet<DataPersona>(0);

    public DataContacto() {
    }

    public DataContacto(String correoElectronico, String telefonoMovil, String telefonoFijo, Set<DataPersona> dataPersonas) {
       this.correoElectronico = correoElectronico;
       this.telefonoMovil = telefonoMovil;
       this.telefonoFijo = telefonoFijo;
       this.dataPersonas = dataPersonas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_contacto", unique=true, nullable=false)
    public Integer getIdContacto() {
        return this.idContacto;
    }
    
    public void setIdContacto(Integer idContacto) {
        this.idContacto = idContacto;
    }

    
    @Column(name="correo_electronico")
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }

    
    @Column(name="telefono_movil", length=15)
    public String getTelefonoMovil() {
        return this.telefonoMovil;
    }
    
    public void setTelefonoMovil(String telefonoMovil) {
        this.telefonoMovil = telefonoMovil;
    }

    
    @Column(name="telefono_fijo", length=15)
    public String getTelefonoFijo() {
        return this.telefonoFijo;
    }
    
    public void setTelefonoFijo(String telefonoFijo) {
        this.telefonoFijo = telefonoFijo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dataContacto")
    public Set<DataPersona> getDataPersonas() {
        return this.dataPersonas;
    }
    
    public void setDataPersonas(Set<DataPersona> dataPersonas) {
        this.dataPersonas = dataPersonas;
    }




}


