package beans;
// Generated 12/03/2018 12:07:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DataDireccion generated by hbm2java
 */
@Entity
@Table(name="data_direccion"
    ,catalog="consultorio_dental"
)
public class DataDireccion  implements java.io.Serializable {


     private Integer idDireccion;
     private CatEstado catEstado;
     private CatPais catPais;
     private String calle;
     private String colonia;
     private String cp;
     private String noInterior;
     private String noExterior;
     private String municipio;
     private Set<DataPersona> dataPersonas = new HashSet<DataPersona>(0);

    public DataDireccion() {
    }

    public DataDireccion(CatEstado catEstado, CatPais catPais, String calle, String colonia, String cp, String noInterior, String noExterior, String municipio, Set<DataPersona> dataPersonas) {
       this.catEstado = catEstado;
       this.catPais = catPais;
       this.calle = calle;
       this.colonia = colonia;
       this.cp = cp;
       this.noInterior = noInterior;
       this.noExterior = noExterior;
       this.municipio = municipio;
       this.dataPersonas = dataPersonas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_direccion", unique=true, nullable=false)
    public Integer getIdDireccion() {
        return this.idDireccion;
    }
    
    public void setIdDireccion(Integer idDireccion) {
        this.idDireccion = idDireccion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="estado")
    public CatEstado getCatEstado() {
        return this.catEstado;
    }
    
    public void setCatEstado(CatEstado catEstado) {
        this.catEstado = catEstado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pais")
    public CatPais getCatPais() {
        return this.catPais;
    }
    
    public void setCatPais(CatPais catPais) {
        this.catPais = catPais;
    }

    
    @Column(name="calle")
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }

    
    @Column(name="colonia")
    public String getColonia() {
        return this.colonia;
    }
    
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }

    
    @Column(name="cp", length=10)
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }

    
    @Column(name="no_interior", length=5)
    public String getNoInterior() {
        return this.noInterior;
    }
    
    public void setNoInterior(String noInterior) {
        this.noInterior = noInterior;
    }

    
    @Column(name="no_exterior", length=5)
    public String getNoExterior() {
        return this.noExterior;
    }
    
    public void setNoExterior(String noExterior) {
        this.noExterior = noExterior;
    }

    
    @Column(name="municipio")
    public String getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dataDireccion")
    public Set<DataPersona> getDataPersonas() {
        return this.dataPersonas;
    }
    
    public void setDataPersonas(Set<DataPersona> dataPersonas) {
        this.dataPersonas = dataPersonas;
    }




}


